export const initialValues = {
  id: "",
  label: "",
  description: "",
  source: "",
  dataset: "",
  unit: "",
  unitSymbol: "",
  precision: 0,
  ranking: 0,
  hidden: false,
  showChart: false,
  absolute: false,
  searchTags: [],
}
