import Header from "@/components/header/Header"
import "@/styles/globals.css"
import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import Footer from "@/components/footer/Footer"
import AlertProvider from "@/providers/alert-provider/AlertProvider"
import ModalProvider from "@/providers/modal-provider/ModalProvider"
import { PropsWithChildren } from "react"
import { Analytics } from "@vercel/analytics/react"
import "@/styles/global.scss"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-neutral-50`}>
        <AlertProvider>
          <ModalProvider>
            <Header />
            {children}
            <Footer />
            <div id="portal" />
            <Analytics />
          </ModalProvider>
        </AlertProvider>
      </body>
    </html>
  )
}
