import Header from '@/components/Header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import getClientId from '@/app/actions/getClientId'
import { randomUUID } from 'crypto'
import { cookies } from 'next/headers'

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-neutral-50`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
