const countries: { [key: string]: { label: string | null } } = {
  ABW: { label: 'Aruba' },
  AFG: { label: 'Afghanistan' },
  AGO: { label: 'Angola' },
  AIA: { label: 'Anguilla' },
  ALB: { label: 'Albania' },
  ARE: { label: 'United Arab Emirates' },
  ARG: { label: 'Argentina' },
  ARM: { label: 'Armenia' },
  ASM: { label: 'American Samoa' },
  ATG: { label: 'Antigua and Barbuda' },
  AUS: { label: 'Australia' },
  AUT: { label: 'Austria' },
  AZE: { label: 'Azerbaijan' },
  BDI: { label: 'Burundi' },
  BEL: { label: 'Belgium' },
  BEN: { label: 'Benin' },
  BFA: { label: 'Burkina Faso' },
  BGD: { label: 'Bangladesh' },
  BGR: { label: 'Bulgaria' },
  BHR: { label: 'Bahrain' },
  BHS: { label: 'Bahamas, The' },
  BIH: { label: 'Bosnia and Herzegovina' },
  BLR: { label: 'Belarus' },
  BLZ: { label: 'Belize' },
  BMU: { label: 'Bermuda' },
  BOL: { label: 'Bolivia' },
  BRA: { label: 'Brazil' },
  BRB: { label: 'Barbados' },
  BRN: { label: 'Brunei Darussalam' },
  BTN: { label: 'Bhutan' },
  BWA: { label: 'Botswana' },
  CAF: { label: 'Central African Republic' },
  CAN: { label: 'Canada' },
  CHE: { label: 'Switzerland' },
  CHI: { label: 'Channel Islands' },
  CHL: { label: 'Chile' },
  CHN: { label: "China, People's Republic of" },
  CIV: { label: "C\u00f4te d'Ivoire" },
  CMR: { label: 'Cameroon' },
  COD: { label: 'Congo, Dem. Rep. of the' },
  COG: { label: 'Congo, Republic of ' },
  COK: { label: 'Cook Islands' },
  COL: { label: 'Colombia' },
  COM: { label: 'Comoros' },
  CPV: { label: 'Cabo Verde' },
  CRI: { label: 'Costa Rica' },
  CUB: { label: 'Cuba' },
  CYM: { label: 'Cayman Islands' },
  CYP: { label: 'Cyprus' },
  CZE: { label: 'Czech Republic' },
  DEU: { label: 'Germany' },
  DJI: { label: 'Djibouti' },
  DMA: { label: 'Dominica' },
  DNK: { label: 'Denmark' },
  DOM: { label: 'Dominican Republic' },
  DZA: { label: 'Algeria' },
  ECU: { label: 'Ecuador' },
  EGY: { label: 'Egypt' },
  ERI: { label: 'Eritrea' },
  ESH: { label: 'Western Sahara' },
  ESP: { label: 'Spain' },
  EST: { label: 'Estonia' },
  ETH: { label: 'Ethiopia' },
  FIN: { label: 'Finland' },
  FJI: { label: 'Fiji' },
  FLK: { label: 'Falkland Islands' },
  FRA: { label: 'France' },
  FRO: { label: 'Faeroe Islands' },
  FSM: { label: 'Micronesia, Fed. States of' },
  GAB: { label: 'Gabon' },
  GBR: { label: 'United Kingdom' },
  GEO: { label: 'Georgia' },
  GHA: { label: 'Ghana' },
  GIB: { label: 'Gibraltar' },
  GIN: { label: 'Guinea' },
  GLP: { label: 'Guadeloupe' },
  GMB: { label: 'Gambia, The' },
  GNB: { label: 'Guinea-Bissau' },
  GNQ: { label: 'Equatorial Guinea' },
  GRC: { label: 'Greece' },
  GRD: { label: 'Grenada' },
  GRL: { label: 'Greenland' },
  GTM: { label: 'Guatemala' },
  GUF: { label: 'French Guiana' },
  GUM: { label: 'Guam' },
  GUY: { label: 'Guyana' },
  HKG: { label: 'Hong Kong SAR' },
  HND: { label: 'Honduras' },
  HRV: { label: 'Croatia' },
  HTI: { label: 'Haiti' },
  HUN: { label: 'Hungary' },
  IDN: { label: 'Indonesia' },
  IMY: { label: 'Isle of Man' },
  IND: { label: 'India' },
  IRL: { label: 'Ireland' },
  IRN: { label: 'Iran' },
  IRQ: { label: 'Iraq' },
  ISL: { label: 'Iceland' },
  ISR: { label: 'Israel' },
  ITA: { label: 'Italy' },
  JAM: { label: 'Jamaica' },
  JOR: { label: 'Jordan' },
  JPN: { label: 'Japan' },
  KAZ: { label: 'Kazakhstan' },
  KEN: { label: 'Kenya' },
  KGZ: { label: 'Kyrgyz Republic' },
  KHM: { label: 'Cambodia' },
  KIR: { label: 'Kiribati' },
  KNA: { label: 'Saint Kitts and Nevis' },
  KOR: { label: 'Korea, Republic of' },
  KWT: { label: 'Kuwait' },
  LAO: { label: 'Lao P.D.R.' },
  LBN: { label: 'Lebanon' },
  LBR: { label: 'Liberia' },
  LBY: { label: 'Libya' },
  LCA: { label: 'Saint Lucia' },
  LIE: { label: 'Liechtenstein' },
  LKA: { label: 'Sri Lanka' },
  LSO: { label: 'Lesotho' },
  LTU: { label: 'Lithuania' },
  LUX: { label: 'Luxembourg' },
  LVA: { label: 'Latvia' },
  MAC: { label: 'Macao SAR' },
  MAR: { label: 'Morocco' },
  MCO: { label: 'Monaco' },
  MDA: { label: 'Moldova' },
  MDG: { label: 'Madagascar' },
  MDV: { label: 'Maldives' },
  MEX: { label: 'Mexico' },
  MHL: { label: 'Marshall Islands' },
  MKD: { label: 'North Macedonia ' },
  MLI: { label: 'Mali' },
  MLT: { label: 'Malta' },
  MMR: { label: 'Myanmar' },
  MNE: { label: 'Montenegro' },
  MNG: { label: 'Mongolia' },
  MNP: { label: 'Northern Mariana Islands' },
  MOZ: { label: 'Mozambique' },
  MRT: { label: 'Mauritania' },
  MSR: { label: 'Montserrat' },
  MTQ: { label: 'Martinique' },
  MUS: { label: 'Mauritius' },
  MWI: { label: 'Malawi' },
  MYS: { label: 'Malaysia' },
  MYT: { label: 'Mayotte' },
  NAM: { label: 'Namibia' },
  NCL: { label: 'New Caledonia' },
  NER: { label: 'Niger' },
  NGA: { label: 'Nigeria' },
  NIC: { label: 'Nicaragua' },
  NIU: { label: 'Niue' },
  NLD: { label: 'Netherlands' },
  NOR: { label: 'Norway' },
  NPL: { label: 'Nepal' },
  NRU: { label: 'Nauru' },
  NZL: { label: 'New Zealand' },
  OMN: { label: 'Oman' },
  PAK: { label: 'Pakistan' },
  PAN: { label: 'Panama' },
  PCN: { label: 'Pitcairn' },
  PER: { label: 'Peru' },
  PHL: { label: 'Philippines' },
  PLW: { label: 'Palau' },
  PNG: { label: 'Papua New Guinea' },
  POL: { label: 'Poland' },
  PRI: { label: 'Puerto Rico' },
  PRK: { label: "Korea, Dem. People's Rep. of" },
  PRT: { label: 'Portugal' },
  PRY: { label: 'Paraguay' },
  PYF: { label: 'French Polynesia' },
  QAT: { label: 'Qatar' },
  REU: { label: 'Reunion' },
  ROU: { label: 'Romania' },
  RUS: { label: 'Russian Federation' },
  RWA: { label: 'Rwanda' },
  SAU: { label: 'Saudi Arabia' },
  SDN: { label: 'Sudan' },
  SEN: { label: 'Senegal' },
  SGP: { label: 'Singapore' },
  SHN: { label: 'Saint Helena' },
  SJM: { label: 'Svalbard and Jan Mayen Islands' },
  SLB: { label: 'Solomon Islands' },
  SLE: { label: 'Sierra Leone' },
  SLV: { label: 'El Salvador' },
  SMR: { label: 'San Marino' },
  SOM: { label: 'Somalia' },
  SPM: { label: 'Saint-Pierre and Miquelon' },
  SRB: { label: 'Serbia' },
  STP: { label: 'S\u00e3o Tom\u00e9 and Pr\u00edncipe' },
  SUR: { label: 'Suriname' },
  SVK: { label: 'Slovak Republic' },
  SVN: { label: 'Slovenia' },
  SWE: { label: 'Sweden' },
  SWZ: { label: 'Eswatini' },
  SYC: { label: 'Seychelles' },
  SYR: { label: 'Syria' },
  TCA: { label: 'Turks and Caicos Islands' },
  TCD: { label: 'Chad' },
  TGO: { label: 'Togo' },
  THA: { label: 'Thailand' },
  TJK: { label: 'Tajikistan' },
  TKL: { label: 'Tokelau' },
  TKM: { label: 'Turkmenistan' },
  TLS: { label: 'Timor-Leste' },
  TON: { label: 'Tonga' },
  TTO: { label: 'Trinidad and Tobago' },
  TUN: { label: 'Tunisia' },
  TUR: { label: 'T\u00fcrkiye, Republic of' },
  TUV: { label: 'Tuvalu' },
  TWN: { label: 'Taiwan Province of China' },
  TZA: { label: 'Tanzania' },
  UGA: { label: 'Uganda' },
  UKR: { label: 'Ukraine' },
  URY: { label: 'Uruguay' },
  USA: { label: 'United States' },
  UZB: { label: 'Uzbekistan' },
  UVK: { label: 'Kosovo' },
  VAT: { label: 'Holy See' },
  VCT: { label: 'Saint Vincent and the Grenadines' },
  VEN: { label: 'Venezuela' },
  VGB: { label: 'British Virgin Islands' },
  VIR: { label: 'United States Virgin Islands ' },
  VNM: { label: 'Vietnam' },
  VUT: { label: 'Vanuatu' },
  WBG: { label: 'West Bank and Gaza' },
  WLF: { label: 'Wallis and Futuna Islands' },
  WSM: { label: 'Samoa' },
  YEM: { label: 'Yemen' },
  ZAF: { label: 'South Africa' },
  ZMB: { label: 'Zambia' },
  ZWE: { label: 'Zimbabwe' },
  SSD: { label: 'South Sudan, Republic of' },
  BNR: { label: 'Bonaire' },
  CUW: { label: 'Curacao' },
  MFX: { label: 'Saint Martin' },
  SXM: { label: 'Sint Maarten' },
  ATI: { label: null },
  ATL: { label: null },
  AND: { label: 'Andorra' },
  AFQ: { label: 'Africa (Region)' },
  AFRREO: { label: 'African Regional Economic Outlook' },
  APQ: { label: 'Asia and Pacific' },
  AZQ: { label: 'Australia and New Zealand' },
  CAQ: { label: 'Central Asia and the Caucasus' },
  CBQ: { label: 'Caribbean' },
  CMQ: { label: 'Central America' },
  EAQ: { label: 'East Asia' },
  EEQ: { label: 'Eastern Europe ' },
  EUQ: { label: 'Europe' },
  MEQ: { label: 'Middle East (Region)' },
  NAQ: { label: 'North Africa' },
  NMQ: { label: 'North America' },
  PIQ: { label: 'Pacific Islands ' },
  SAQ: { label: 'South Asia' },
  SEQ: { label: 'Southeast Asia' },
  SMQ: { label: 'South America' },
  SSQ: { label: 'Sub-Saharan Africa (Region) ' },
  WEQ: { label: 'Western Europe' },
  WHQ: { label: 'Western Hemisphere (Region)' },
  AFR_SSQ: { label: 'Sub-Saharan Africa (Region) ' },
  SPR_GD_MECA: { label: 'Middle East and Central Asia' },
  SPR_GD_EUR: { label: 'Europe' },
  SPR_GD_AFR: { label: 'Africa' },
  SPR_GD_CPI: { label: 'Caribbean and Pacific Islands' },
  SPR_GD_WHD: { label: 'Western Hemisphere' },
  SPR_GD_Asia: { label: 'Asia' },
  ADVEC: { label: 'Advanced economies' },
  AEEUEJ: { label: 'Adv econ excl US, Euro, Japan' },
  AFR: { label: 'Africa (Analytical)' },
  AS5: { label: 'ASEAN-5' },
  CEE: { label: 'Central and Eastern Europe' },
  CEMAC: { label: 'CEMAC' },
  CFAFZ: { label: 'CFA Franc Zone ' },
  CISM: { label: 'Commonwealth of Independent States and Mongolia' },
  COMESA: { label: 'COMESA (SSA members)' },
  DA: { label: 'Emerging and Developing Asia' },
  EAC: { label: 'East African Community ' },
  'EAC-5': { label: 'East African Community ' },
  EEF: { label: 'Export earnings: fuel' },
  EENF: { label: 'Export earnings: nonfuel' },
  EU: { label: 'European Union' },
  EUR: { label: 'Europe' },
  EURO: { label: 'Euro area' },
  EUROAREA: { label: 'Euro area' },
  FLERRC: { label: 'Countries without conventional exchange rate pegs' },
  FRC: { label: 'Countries in fragile and conflict-affected situations' },
  FXERRC: { label: 'Countries with conventional exchange rate pegs' },
  LIC: { label: 'Low-income countries' },
  LL: { label: 'Landlocked' },
  MAE: { label: 'Major advanced economies (G7)' },
  MAF: { label: 'Emerging Asia excl Japan incl NIEs' },
  MCA: { label: 'EM and dev econ incl sel adv econ' },
  MDRI: { label: 'MDRI countries ' },
  ME: { label: 'Middle East (Analytical)' },
  MENA: { label: 'Middle East and North Africa' },
  MIC: { label: 'Middle-income countries' },
  MIC854: { label: 'MICs excluding Nigeria and South Africa ' },
  NO824: { label: 'Non-oil' },
  NONC872: { label: 'Coastal  ' },
  NONRESINT: { label: 'Non-resource-intensive countires  ' },
  OAE: { label: 'Other advanced economies' },
  OEMDC: { label: 'Emerging market and developing economies' },
  OEXP: { label: 'Oil-exporting countries' },
  OIM808: { label: 'Oil-importing countries excluding South Africa ' },
  OIMP: { label: 'Oil-importing countries ' },
  OTH: { label: 'Other Groups' },
  OXEN853: { label: 'Oil-exporting countries excluding Nigeria ' },
  PRGF: { label: 'Countries eligible for PRGF' },
  RESINT: { label: 'Resource-intensive countries  ' },
  SACU: { label: 'SACU' },
  SADC: { label: 'SADC' },
  SSA: { label: 'Sub-Saharan Africa' },
  WAEMU: { label: 'WAEMU' },
  WE: { label: 'Latin America and the Caribbean' },
  WEOWORLD: { label: 'World' },
  FAD_WORLD: { label: 'World' },
  FAD_G20: { label: 'G-20' },
  FAD_G20Adv: { label: 'G-20 Advanced' },
  FAD_G20Emg: { label: 'G-20 Emerging' },
  FAD_LIC: { label: 'Low Income' },
  LICXF: { label: 'LICs excluding low income countries in fragile and conflict-affected situations' },
  SSENS: { label: 'SSA excluding Nigeria and South Africa ' },
  FM_EMG: { label: 'Emerging Market and Middle-Income Economies' },
  SSXZ: { label: 'SSA excluding Zimbabwe' },
  SSXSD: { label: 'Sub-Saharan Africa, excluding South Sudan' },
  MENAP: { label: 'Middle East, North Africa, Afghanistan, and Pakistan' },
  ECOWAS: { label: 'Economic Community of West African States' },
  BOPWORLD: { label: 'World' },
  IIO: { label: 'International Organizations' },
  EDE: { label: 'Emerging and Developing Europe' },
  FM_LIC: { label: 'Low-Income Countries' },
  FM_AdvG20: { label: 'Advanced G-20' },
  FM_EMEG20: { label: 'Emerging G-20' },
  FM_EMEEU: { label: 'Emerging and Middle-Income Europe' },
  FM_EMEAsia: { label: 'Emerging and Middle-Income Asia' },
  FM_EMELA: { label: 'Emerging and Middle-Income Latin America' },
  FM_EMEME: { label: 'Emerging and Middle-Income Middle East and North Africa and Pakistan' },
  FM_LICAsia: { label: 'Low-Income Developing Asia' },
  FM_LICLA: { label: 'Low-Income Developing Latin America' },
  FM_LICSSA: { label: 'Low-Income Developing Sub-Saharan Africa' },
  FM_LICO: { label: 'Low-Income Developing Others' },
  FM_LICOP: { label: 'Low-Income Developing Oil Producers' },
  FM_LIDC: { label: 'Low-Income Developing Countries' },
  CIS: { label: 'Commonwealth of Independent States' },
  CFWORLD: { label: 'World' },
  ARAWORLD: { label: 'World' },
  SPR_HIC: { label: 'High Income Countries (median)' },
  SPR_LIDC: { label: 'Low-Income Developing Countries (median)' },
  SPR_FLIDC: { label: 'Frontier LIDCs (median)' },
  SPR_GD_AM: { label: 'Advanced Economies' },
  SPR_GD_LIDC: { label: 'Low Income Developing Countries' },
  SPR_GD_EM: { label: 'Emerging Markets' },
  gbtier_1: { label: 'Prominent gender budgeting countries covered in the surveys' },
  gbtier_2: { label: 'Other gender budgeting countries covered in the surveys' },
  gbcasestudy: { label: 'Identified as gender budgeting country in IMF regional survey' },
  gb_othersource: { label: 'Other countries' },
  GDWORLD: { label: 'World' },
  ECCU: { label: 'Eastern Caribbean Currency Union' },
  FAD_C1: { label: 'Catergory I' },
  FAD_NG20: { label: 'Non G-20' },
  FAD_C2: { label: 'Catergory II' },
  FAD_OP: { label: 'Oil Producers' },
  FAD_NOHIC: { label: 'Non-Oil High Income' },
  FAD_NOMIC: { label: 'Non-Oil Middle Income' },
  FAD_NOLIC: { label: 'Non-Oil Low Income' },
  FAD_C3: { label: 'Catergory III' },
  FAD_NOFAST: { label: 'Non-Oil Fast' },
  FAD_NOMED: { label: 'Non-Oil Medium' },
  FAD_NOSLOW: { label: 'Non-Oil Slow' },
  FAD_C4: { label: 'Catergory IV' },
  FAD_G7: { label: 'G-7' },
  FAD_NG7: { label: 'None G-7' },
  FAD_C5: { label: 'Catergory V' },
  FAD_EuroArea: { label: 'Euro Area' },
  FAD_EMAsia: { label: 'Emerging Asia' },
  FAD_OtherAdv: { label: 'Other Advanced' },
  FAD_Rest: { label: 'Rest' },
  FAD_C6: { label: 'Catergory VI' },
  FAD_WHD: { label: 'Western Hemisphere Group' },
  FAD_MCD: { label: 'Middle East and Central Asia Group' },
  FAD_APD: { label: 'Asia & Pacific Group' },
  FAD_AFR: { label: 'African Group' },
  FAD_EUR: { label: 'European Group' },
  FAD_ADV: { label: 'Advanced Economies' },
  FAD_EME: { label: 'Emerging Market' },
  FAD_EMD: { label: 'Emerging and Developing Countries ' },
  FADGDWORLD: { label: 'All countries - Global Debt' },
  MECA: { label: 'Middle East and Central Asia' },
  CCWORLD: { label: 'World' },
  FR_FCWORLD: { label: 'All countries - Fiscal Rules & Fiscal Councils' },
  FR_FC_ADV: { label: 'Advanced Economies' },
  FR_FC_EME: { label: 'Emerging Market and Developing Economies' },
  FR_FC_EU: { label: 'European Union' },
  FR_FC_NonEU: { label: 'Non European Union' },
}

const getFullCountryName = (key: string) => {
  return (countries[key] && countries[key].label) || 'No Data'
}

export default getFullCountryName
