name: CI / Testing

on:
  push:
    branches:
      - "**"

jobs:
  build:
    env:
      AUTH_SECRET: "secret"
      DATABASE_URL: "postgresql://postgres:1111@localhost:5432/statify"
      RESULTS_PER_PAGE: "45"
      NEXT_PUBLIC_SERVER_ADDRESS: "http://localhost:3000"
      NEXT_PUBLIC_IMAGES_HOSTING_ADDRESS: "https://statify-images.netlify.app"
      NEXT_PUBLIC_LANG: "en"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: core/package-lock.json
          cache: "npm"

      - name: Install dependencies
        working-directory: core
        run: npm ci

      - name: Run ESLint
        working-directory: core
        run: npm run lint

      - name: Rub tests
        working-directory: core
        run: npm test -- --coverage
