name: CI / Testing

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  build:
    env:
      AUTH_SECRET: "secret"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm test
